namespace MyResult.SourceGenerator.Templates;

internal static class ResultAttributeTemplate
{
    public const string Namespace = "MyResult";

    public const string Name = "ResultAttribute";

    public const string FullName = $"{Namespace}.{Name}";

    public static string Generate()
    {
        return $$"""
               // <auto-generated />

               #nullable enable

               namespace {{Namespace}}
               {
                   [System.AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
                   internal sealed class {{Name}} : System.Attribute
                   {
                       public {{Name}}(Type? errorType = null, bool hasImplicitConversion = true)
                       {
                       }
                   }
               }
               """;
    }
}